version: "3.8"
services:
  server:
    image: "${PROJECT_NAME}-server"
    build:
      context: .
      target: server
    container_name: "${PROJECT_NAME}-server"
    restart: always
    links:
      - database:tmr.database
    volumes:
      - ./docker/volumes/logs/server:/logs/server:rw
      - ./docker/volumes/storage:/storage:rw
      - ./docker/volumes/.env.server:/app/.env:rw
      - ./docker/volumes/entrypoint.server.sh:/app/entrypoint.sh:rw
      - ./server:/app:rw
  database:
    image: mongo:7.0.2-jammy
    container_name: "${PROJECT_NAME}-db"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./docker/volumes/initdb:/docker-entrypoint-initdb.d
      - ./docker/volumes/mongo:/data/db
  database-interface:
    image: mongo-express:1.0.0-20-alpine3.18
    container_name: "${PROJECT_NAME}-dbi"
    restart: always
    links:
      - database:tmr.database
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@tmr.database:${MONGO_PORT}/${MONGO_DATABASE}"
  proxy:
    image: nginx:stable-alpine3.17
    container_name: "${PROJECT_NAME}-proxy"
    links:
      - server:tmr.server
    ports:
      - 443:443
    environment:
      - NGINX_HOST=tmr.api.local
      - NGINX_PORT=443
    volumes:
      - ./docker/volumes/ssl:/ssl:r
      - ./docker/volumes/nginx:/etc/nginx/templates
      - ./docker/volumes/logs/nginx:/var/log/nginx:rw
